import React, {FC} from 'react'

import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.scss'
import base from '../styles/index.module.scss'
// import '../styles/index.scss'

const Home: FC = () => {
  console.log('process.env.NODE_ENV', process.env.NODE_ENV)
  console.log('process.env.NEXT_PUBLIC_NODE_ENV2', process.env.NEXT_PUBLIC_NODE_ENV2)
  return (
    <div className="container">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <p>もろもろ実験</p>

      <Link href="/about">
        練習場
      </Link>

      <Link href="/imageChange">
        SVGを編集してcanvas使ってpng画像をNextJSで作ってみよう
      </Link>

      <p>画像を配置1</p>
    <Image
      src={"/vercel.svg"}
      alt="Picture of the author"
      width={200}
      height={200}
    />

    <p>画像を配置2</p>
    <img src={ `/vercel.svg` } />

    <h1 className={styles.title}>
      <span className={ base.fuga }>Welcome to</span> <a href="https://nextjs.org">Next.js!</a>
    </h1>
    </div>
  )
}


export default Home
